Repository DevsFromBels/project-titan, pull requests merged in 2024-04, with the labels that each got.

#1 Feature/graphql
  web/.env
  web/package-lock.json
  web/package.json
  web/src/app/layout.tsx
  web/src/shared/Providers/ApolloProvider.tsx
  web/src/shared/components/ui/tooltip.tsx
  web/src/shared/graphql/actions/activation.action.ts
  web/src/shared/graphql/actions/get-user.action.ts
  web/src/shared/graphql/actions/login.action.ts
  web/src/shared/graphql/actions/logout.action.ts
  web/src/shared/graphql/actions/profile/getProfile.action.ts
  web/src/shared/graphql/actions/register.action.ts
  web/src/shared/graphql/gql.setup.ts
Labels: enhancement

#2 feat(): inited core
  .DS_Store
  core/.DS_Store
  core/.env.local
  core/.gitignore
  core/README.md
  core/apps/gateway/src/app.module.ts
  core/apps/gateway/src/app.service.ts
  core/apps/gateway/src/context.ts
  core/apps/gateway/src/main.ts
  core/apps/gateway/test/app.e2e-spec.ts
  core/apps/gateway/test/jest-e2e.json
  core/apps/gateway/tsconfig.app.json
  core/apps/profile/src/dto/profile.dto.ts
  core/apps/profile/src/entities/profile.entitie.ts
  core/apps/profile/src/guards/auth.guard.ts
  core/apps/profile/src/main.ts
  core/apps/profile/src/profile.module.ts
  core/apps/profile/src/profile.resolver.spec.ts
  core/apps/profile/src/profile.resolver.ts
  core/apps/profile/src/profile.service.ts
  core/apps/profile/src/types/porfile.types.ts
  core/apps/profile/test/app.e2e-spec.ts
  core/apps/profile/test/jest-e2e.json
  core/apps/profile/tsconfig.app.json
  core/apps/users/src/dto/user.dto.ts
  core/apps/users/src/email/email.module.ts
  core/apps/users/src/email/email.service.spec.ts
  core/apps/users/src/email/email.service.ts
  core/apps/users/src/entities/user.entity.ts
  core/apps/users/src/guards/auth.guard.ts
  core/apps/users/src/main.ts
  core/apps/users/src/types/users.types.ts
  core/apps/users/src/users.module.ts
  core/apps/users/src/users.resolver.ts
  core/apps/users/src/users.service.ts
  core/apps/users/src/utils/sendToken.ts
  core/apps/users/tsconfig.app.json
  core/bun.lockb
  core/dist/apps/gateway/main.js
  core/dist/apps/profile/main.js
  core/dist/apps/users/main.js
  core/docker-compose.yml
  core/ecosystem.config.js
  core/email-templates/activation-mail.ejs
  core/nest-cli.json
  core/package-lock.json
  core/package.json
  core/prisma/prisma.service.ts
  core/prisma/schema.prisma
  core/tsconfig.build.json
  core/tsconfig.json
  web/src/app/layout.tsx
Labels: enhancement

#3 Feature/not found
  web/package-lock.json
  web/package.json
  web/src/app/[...not_found]/page.tsx
  web/src/app/error.tsx
  web/src/app/global-error.tsx
  web/src/app/layout.tsx
Labels: enhancement

#4 feat(): complete v0.1
  .DS_Store
  core/.DS_Store
  core/.env.local
  core/.gitignore
  core/README.md
  core/apps/gateway/src/app.module.ts
  core/apps/gateway/src/app.service.ts
  core/apps/gateway/src/context.ts
  core/apps/gateway/src/main.ts
  core/apps/gateway/test/app.e2e-spec.ts
  core/apps/gateway/test/jest-e2e.json
  core/apps/gateway/tsconfig.app.json
  core/apps/profile/src/dto/profile.dto.ts
  core/apps/profile/src/entities/profile.entitie.ts
  core/apps/profile/src/guards/auth.guard.ts
  core/apps/profile/src/main.ts
  core/apps/profile/src/profile.module.ts
  core/apps/profile/src/profile.resolver.spec.ts
  core/apps/profile/src/profile.resolver.ts
  core/apps/profile/src/profile.service.ts
  core/apps/profile/src/types/porfile.types.ts
  core/apps/profile/test/app.e2e-spec.ts
  core/apps/profile/test/jest-e2e.json
  core/apps/profile/tsconfig.app.json
  core/apps/users/src/dto/user.dto.ts
  core/apps/users/src/email/email.module.ts
  core/apps/users/src/email/email.service.spec.ts
  core/apps/users/src/email/email.service.ts
  core/apps/users/src/entities/user.entity.ts
  core/apps/users/src/guards/auth.guard.ts
  core/apps/users/src/main.ts
  core/apps/users/src/types/users.types.ts
  core/apps/users/src/users.module.ts
  core/apps/users/src/users.resolver.ts
  core/apps/users/src/users.service.ts
  core/apps/users/src/utils/sendToken.ts
  core/apps/users/tsconfig.app.json
  core/bun.lockb
  core/dist/apps/gateway/main.js
  core/dist/apps/profile/main.js
  core/dist/apps/users/main.js
  core/docker-compose.yml
  core/ecosystem.config.js
  core/email-templates/activation-mail.ejs
  core/nest-cli.json
  core/package-lock.json
  core/package.json
  core/prisma/prisma.service.ts
  core/prisma/schema.prisma
  core/tsconfig.build.json
  core/tsconfig.json
Labels: enhancement

#6 feat(): profile search
  core/apps/profile/src/entities/profile.entitie.ts
  core/apps/profile/src/profile.resolver.ts
  core/apps/profile/src/profile.service.ts
  core/dist/apps/profile/main.js
Labels: enhancement

#7 feat(): profile search (#6)
  core/apps/profile/src/entities/profile.entitie.ts
  core/apps/profile/src/profile.resolver.ts
  core/apps/profile/src/profile.service.ts
  core/dist/apps/profile/main.js
Labels: enhancement

#9 ipv6 to v4
  core/.gitignore
  core/apps/gateway/src/context.ts
  core/apps/gateway/src/main.ts
  core/apps/profile/src/main.ts
  core/dist/apps/gateway/main.js
  core/dist/apps/profile/main.js
Labels: bug, enhancement

#10 chore(): try to bux fix
  core/apps/gateway/src/main.ts
  core/apps/profile/src/main.ts
  core/dist/apps/profile/main.js
Labels: bug

#13 chore(): bug fix cors(204) problems
  core/apps/gateway/src/main.ts
  web/src/shared/components/organisms/header/header.tsx
Labels: enhancement

#15 feat(): mobile deep-link, and inited sso
  sso/.gitignore
  sso/.vscode/extensions.json
  sso/README.md
  sso/components.json
  sso/env.d.ts
  sso/index.html
  sso/package-lock.json
  sso/package.json
  sso/public/favicon.ico
  sso/src/App.vue
  sso/src/assets/base.css
  sso/src/assets/logo.svg
  sso/src/graphql/login-user-query.ts
  sso/src/main.ts
  sso/src/router/index.ts
  sso/src/views/SignIn.vue
  sso/src/views/SignUp.vue
  sso/tailwind.config.ts
  sso/tsconfig.app.json
  sso/tsconfig.json
  sso/tsconfig.node.json
  sso/vite.config.ts
  web/src/app/(auth)/sign-in/page.tsx
  web/src/shared/components/organisms/wanna-mobile/wanna-mobile.tsx
  web/src/shared/graphql/gql.setup.ts
  web/src/shared/pages/auth/sign-in.tsx
Labels: enhancement

#17 Test mobile deep link
  .DS_Store
  sso/index.html
  sso/src/views/SignIn.vue
  web/src/app/layout.tsx
Labels: enhancement

#20 feat(): created admin panel
  admin/.editorconfig
  admin/.gitignore
  admin/.vscode/extensions.json
  admin/.vscode/launch.json
  admin/.vscode/tasks.json
  admin/README.md
  admin/angular.json
  admin/package-lock.json
  admin/package.json
  admin/src/app/app.component.css
  admin/src/app/app.component.html
  admin/src/app/app.component.ts
  admin/src/app/app.config.ts
  admin/src/app/app.routes.ts
  admin/src/app/graphql.provider.ts
  admin/src/app/notfound/notfound.component.html
  admin/src/app/notfound/notfound.component.ts
  admin/src/app/services/user/user.service.spec.ts
  admin/src/app/services/user/user.service.ts
  admin/src/app/sign-in/sign-in.component.html
  admin/src/app/sign-in/sign-in.component.ts
  admin/src/app/users/users.component.html
  admin/src/app/users/users.component.ts
  admin/src/assets/.gitkeep
  admin/src/assets/icons/lock.svg
  admin/src/components/my-button/my-button.component.html
  admin/src/components/my-button/my-button.component.ts
  admin/src/components/my-input/my-input.component.css
  admin/src/components/my-input/my-input.component.html
  admin/src/components/my-input/my-input.component.spec.ts
  admin/src/components/my-input/my-input.component.ts
  admin/src/components/my-loader/my-loader.component.css
  admin/src/components/my-loader/my-loader.component.html
  admin/src/components/my-loader/my-loader.component.spec.ts
  admin/src/components/my-loader/my-loader.component.ts
  admin/src/components/my-sidebar/my-sidebar.component.css
  admin/src/components/my-sidebar/my-sidebar.component.html
  admin/src/components/my-sidebar/my-sidebar.component.spec.ts
  admin/src/components/my-sidebar/my-sidebar.component.ts
  admin/src/favicon.ico
  admin/src/graphql/login.action.ts
  admin/src/graphql/user-profiles.action.ts
  admin/src/index.html
  admin/src/main.ts
  admin/src/styles.css
  admin/src/types/user.type.ts
  admin/tailwind.config.js
  admin/tsconfig.app.json
  admin/tsconfig.json
  admin/tsconfig.spec.json
Labels: enhancement

#22 feat(): completed web, some bug fix, without validations and error ha…
  admin/angular-start.js
  web/package-lock.json
  web/package.json
  web/public/Logo.svg
  web/public/next.svg
  web/public/vercel.svg
  web/src/app/(auth)/sign-up/page.tsx
  web/src/app/__favicon.ico
  web/src/app/error.tsx
  web/src/app/favicon.ico
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/loading.tsx
  web/src/app/page.tsx
  web/src/app/robots.ts
  web/src/features/auth/auth.ts
  web/src/features/auth/updateTokens.ts
  web/src/features/graphql/actions/activation.action.ts
  web/src/features/graphql/actions/get-user.action.ts
  web/src/features/graphql/actions/login.action.ts
  web/src/features/graphql/actions/logout.action.ts
  web/src/features/graphql/actions/profile/getProfile.action.ts
  web/src/features/graphql/actions/register.action.ts
  web/src/features/graphql/gql.setup.ts
  web/src/features/store/login.store.ts
  web/src/features/store/register.store.ts
  web/src/shared/Providers/ApolloProvider.tsx
  web/src/shared/components/ui/dialog.tsx
  web/src/shared/components/ui/input-otp.tsx
  web/src/shared/components/ui/loader/loader.module.css
  web/src/shared/components/ui/loader/loader.tsx
  web/src/shared/hooks/use-profile.ts
  web/src/shared/hooks/use-user.ts
  web/src/shared/pages/auth/sign-in.tsx
  web/src/shared/pages/auth/sign-up.tsx
  web/src/shared/types/auth.types.ts
  web/src/widgets/header/header.tsx
  web/src/widgets/wanna-mobile/wanna-mobile.tsx
Labels: enhancement
